name: caller
on: push
jobs:
  my-job-start:
    # Importing a reusable workflow from another repository and branch
    uses: expressmailin/github_action/.github/workflows/workflow_called.yml@main
    # Passing 'node-version' as an input parameter to the reusable workflow
    with:
      node-version: '18.x'
